"""empty message

Revision ID: 7a3a3ca8c6d1
Revises: 1a07d3970b6f
Create Date: 2021-11-15 16:00:03.831215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3a3ca8c6d1'
down_revision = '1a07d3970b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccinations', 'dose',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccinations', 'dose',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
